version: '3'

services:

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: world-art-ru-parser
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: parser
    networks:
      - backend
    restart: always

  world-art-ru-parser:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: parser
      POSTGRES_DB: world-art-ru-parser
    ports:
      - "3005:3000"
    networks:
      - backend
    restart: always

networks:
  backend:
